/// <reference types="geojson" />
import type {
  BestPractice,
  Population65Map,
  Principle,
  StaticCountrySnapshot,
} from "../types/staticData";

// All static/* files are generated by scripts/sync-static-data.mjs from the
// repo-root CSVs/geojson (see NEW_FRONTEND_PLAN.md §5.2) and served directly
// as plain files under public/data/ — no API round-trip involved.
const DATA_BASE = "/data";

async function getJson<T>(path: string): Promise<T> {
  const res = await fetch(`${DATA_BASE}/${path}`);
  if (!res.ok) throw new Error(`Failed to load static data file: ${path}`);
  return (await res.json()) as T;
}

export const staticData = {
  principles: () => getJson<Principle[]>("principles.json"),
  bestPractices: () => getJson<BestPractice[]>("best_practices.json"),
  population65: () => getJson<Population65Map>("population_65.json"),
  countrySnapshot: () => getJson<StaticCountrySnapshot>("static_country_snapshot.json"),
  indiaGeojson: () => getJson<GeoJSON.FeatureCollection>("india_outline.geojson"),
};
